// Roman Catholic General Calendar — saints and celebrations by month/day.
// Source: Calendarium Romanum Generale (universal Roman Rite).
// Key: "M-D" (no leading zeros). Value: Kinyarwanda name.
//
// You can add or correct entries here. Days not listed return null
// (no specific celebration shown). Local/diocesan feasts can be added below.

const SAINTS: Record<string, string> = {
  // ── January ──────────────────────────────────────────────────────────────
  "1-1":  "Mutagatifu Mariya, Nyina wa Imana",
  "1-2":  "Mutagatifu Baziliyasi Nkuru na Mutagatifu Grigori wa Naziyanze",
  "1-7":  "Mutagatifu Rayimondi wa Penyafori",
  "1-13": "Mutagatifu Hilariyoni",
  "1-17": "Mutagatifu Antuwani Abati",
  "1-20": "Mutagatifu Fabiyani na Mutagatifu Sebasitiyani",
  "1-21": "Mutagatifu Agnesite",
  "1-22": "Mutagatifu Vinsani",
  "1-24": "Mutagatifu Fransisiko wa Sali",
  "1-25": "Guturika kwa Mutagatifu Paulo",
  "1-26": "Mutagatifu Timoteyo na Mutagatifu Tito",
  "1-27": "Mutagatifu Anjelika Merici",
  "1-28": "Mutagatifu Toma Akwino",
  "1-31": "Mutagatifu Yohani Bosiko",

  // ── February ─────────────────────────────────────────────────────────────
  "2-2":  "Gutura kwa Yezu mu Hekalu",
  "2-3":  "Mutagatifu Bleyazi na Mutagatifu Ansgari",
  "2-5":  "Mutagatifu Agata",
  "2-6":  "Mutagatifu Paulo Miki n'Inshuti ze",
  "2-8":  "Mutagatifu Jeronimo Emiliyani na Mutagatifu Jozefini Bakhita",
  "2-10": "Mutagatifu Siyolasitika",
  "2-11": "Bikira Mariya wa Luridi",
  "2-14": "Mutagatifu Sirilosi na Mutagatifu Metodiyo",
  "2-17": "Abatagatifu Basatari b'Ubutegetsi bwa Mariya",
  "2-21": "Mutagatifu Petero Damiyani",
  "2-22": "Ntebe ya Mutagatifu Petero",
  "2-23": "Mutagatifu Polikarpo",

  // ── March ────────────────────────────────────────────────────────────────
  "3-4":  "Mutagatifu Kasimiri",
  "3-7":  "Mutagatifu Perpetuwa na Mutagatifu Felisita",
  "3-8":  "Mutagatifu Yohani w'Imana",
  "3-9":  "Mutagatifu Fransisikazi Romani",
  "3-17": "Mutagatifu Patiriki",
  "3-18": "Mutagatifu Sirilyasi Kirikosi",
  "3-19": "Mutagatifu Yozefu, Umugabo wa Bikira Mariya",
  "3-23": "Mutagatifu Turibiyo wa Mogrovejo",
  "3-25": "Guturikirwa kwa Bikira Mariya",

  // ── April ────────────────────────────────────────────────────────────────
  "4-2":  "Mutagatifu Fransisiko wa Paola",
  "4-4":  "Mutagatifu Isidori wa Sivili",
  "4-5":  "Mutagatifu Vinsani Fereryo",
  "4-7":  "Mutagatifu Yohani wa Pahimisi",
  "4-11": "Mutagatifu Stanisilawu",
  "4-13": "Mutagatifu Maretini I",
  "4-21": "Mutagatifu Anselumu",
  "4-23": "Mutagatifu Joriji",
  "4-24": "Mutagatifu Fideli wa Sigimari",
  "4-25": "Mutagatifu Luka (Ubutatambire bwa Mutagatifu Mariko)",
  "4-28": "Mutagatifu Petero Sube na Mutagatifu Luisi Grinyo",
  "4-29": "Mutagatifu Katarini wa Siyena",
  "4-30": "Mutagatifu Piyo V",

  // ── May ──────────────────────────────────────────────────────────────────
  "5-1":  "Mutagatifu Yozefu Umukorikori",
  "5-2":  "Mutagatifu Atanasi",
  "5-3":  "Mutagatifu Filipo na Mutagatifu Yafeti (Intumwa)",
  "5-12": "Mutagatifu Nereyo na Mutagatifu Akile",
  "5-13": "Bikira Mariya wa Fatima",
  "5-14": "Mutagatifu Matiyasi (Intumwa)",
  "5-15": "Mutagatifu Isidori Umuhinzi",
  "5-18": "Mutagatifu Yohani I",
  "5-20": "Mutagatifu Bernarudi wa Siyena",
  "5-22": "Mutagatifu Ruta",
  "5-25": "Mutagatifu Bede Nkuru na Mutagatifu Biriyani",
  "5-26": "Mutagatifu Filipi Neri",
  "5-27": "Mutagatifu Agusitino wa Kanterubeyi",
  "5-31": "Gusura kwa Bikira Mariya kwa Elizabeti",

  // ── June ─────────────────────────────────────────────────────────────────
  "6-1":  "Mutagatifu Yuniyani",
  "6-2":  "Mutagatifu Marselini na Mutagatifu Petero",
  "6-3":  "Abatagatifu b'Uganda — Mutagatifu Karolo Lwanga n'Inshuti ze",
  "6-5":  "Mutagatifu Bonifasi",
  "6-6":  "Mutagatifu Noruberi",
  "6-9":  "Mutagatifu Efiremu w'Asiriya",
  "6-11": "Mutagatifu Barnabase (Intumwa)",
  "6-13": "Mutagatifu Antuwani wa Padowa",
  "6-19": "Mutagatifu Romuwalidi",
  "6-21": "Mutagatifu Aloyizi Gonzaga",
  "6-22": "Mutagatifu Paulino wa Nole, Mutagatifu Yohani Fisheri na Mutagatifu Toma More",
  "6-23": "Mutagatifu Yozefu Kafaso",
  "6-24": "Kuvuka kwa Mutagatifu Yohani Batisita",
  "6-25": "Mutagatifu Eleonora, Mutagatifu Galikani, Mutagatifu Prosperi, na Mutagatifu Wilihelimi",
  "6-26": "Mutagatifu Antelmi na Mutagatifu Salvi",
  "6-27": "Mutagatifu Sirili wa Aleksanderiya",
  "6-28": "Mutagatifu Irene",
  "6-29": "Mutagatifu Petero na Mutagatifu Paulo (Intumwa)",
  "6-30": "Abapfiriye Imana ba mbere i Roma, Mutagatifu Adoifi, Mutagatifu Marsiyali, na Mutagatifu Teobaldi",

  // ── July ─────────────────────────────────────────────────────────────────
  "7-3":  "Mutagatifu Tomasi (Intumwa)",
  "7-4":  "Mutagatifu Elizabeti wa Portugali",
  "7-5":  "Mutagatifu Antuwani Zakkaria",
  "7-6":  "Mutagatifu Mariya Goreti",
  "7-9":  "Mutagatifu Agusitino Zhao Rong n'Inshuti ze",
  "7-11": "Mutagatifu Benedikyito",
  "7-13": "Mutagatifu Henri",
  "7-14": "Mutagatifu Kamiyo wa Leli",
  "7-15": "Mutagatifu Bonaventura",
  "7-16": "Bikira Mariya wa Karumeli",
  "7-20": "Mutagatifu Apolinarisi",
  "7-21": "Mutagatifu Lawuransi wa Brindizi",
  "7-22": "Mutagatifu Mariya Magdalena",
  "7-23": "Mutagatifu Birijita",
  "7-24": "Mutagatifu Sharbeli Maklufu",
  "7-25": "Mutagatifu Yakobo (Intumwa)",
  "7-26": "Mutagatifu Yoakimu na Mutagatifu Ana (Ababyeyi ba Bikira Mariya)",
  "7-29": "Mutagatifu Marta, Mutagatifu Mariya na Mutagatifu Lazaro",
  "7-30": "Mutagatifu Petero Krisologo",
  "7-31": "Mutagatifu Ignasi wa Loyola",

  // ── August ───────────────────────────────────────────────────────────────
  "8-1":  "Mutagatifu Alfonsusi wa Liguori",
  "8-2":  "Mutagatifu Euzebio wa Verceli",
  "8-4":  "Mutagatifu Yohani Viyane",
  "8-5":  "Gushyirwaho gwa Bazirika ya Santa Maria Major",
  "8-6":  "Guhinduka kwa Yezu ku Musozi Tabori",
  "8-7":  "Mutagatifu Sisto II n'Inshuti ze na Mutagatifu Kajetani",
  "8-8":  "Mutagatifu Dominiko",
  "8-9":  "Mutagatifu Tereza Benedikta wa Umusalaba",
  "8-10": "Mutagatifu Lawuransi (Diakoni)",
  "8-11": "Mutagatifu Klara",
  "8-13": "Mutagatifu Pontiyano na Mutagatifu Hipolito",
  "8-14": "Mutagatifu Maksimiliyani Kolbe",
  "8-15": "Kuzamurwa kwa Bikira Mariya mu Ijuru",
  "8-16": "Mutagatifu Stefani wa Ugiriya",
  "8-19": "Mutagatifu Yohani Eudes",
  "8-20": "Mutagatifu Bernarudi wa Kilerivo",
  "8-21": "Mutagatifu Piyo X",
  "8-22": "Bikira Mariya Umwamikazi",
  "8-23": "Mutagatifu Rosa wa Lima",
  "8-24": "Mutagatifu Baritelemayo (Intumwa)",
  "8-25": "Mutagatifu Ludoviko na Mutagatifu Yozefu wa Kalasani",
  "8-27": "Mutagatifu Monika",
  "8-28": "Mutagatifu Agusitino wa Hipono",
  "8-29": "Gukata Umutwe wa Mutagatifu Yohani Batisita",

  // ── September ────────────────────────────────────────────────────────────
  "9-3":  "Mutagatifu Grigori Nkuru",
  "9-5":  "Mutagatifu Tereza wa Kalkuta",
  "9-8":  "Kuvuka kwa Bikira Mariya",
  "9-9":  "Mutagatifu Petero Klaverio",
  "9-12": "Izina Ryera rya Bikira Mariya",
  "9-13": "Mutagatifu Yohani Krisosomu",
  "9-14": "Gutumarizwa kwa Umusalaba Mutagatifu",
  "9-15": "Bikira Mariya w'Amarira",
  "9-16": "Mutagatifu Korneliyo na Mutagatifu Sipriyano",
  "9-17": "Mutagatifu Roberto Belarmino",
  "9-19": "Mutagatifu Januwariyosi",
  "9-20": "Mutagatifu Andire Kim Taegon n'Inshuti ze",
  "9-21": "Mutagatifu Matayo (Intumwa na Umunyamakuru w'Ubutumwa bwiza)",
  "9-23": "Mutagatifu Piyo wa Pietrelcina (Padre Pio)",
  "9-26": "Mutagatifu Kosima na Mutagatifu Damiyani",
  "9-27": "Mutagatifu Vinsani wa Paulo",
  "9-28": "Mutagatifu Wensesila",
  "9-29": "Mutagatifu Mikaeli, Mutagatifu Gaburiyeri na Mutagatifu Rafayeli",
  "9-30": "Mutagatifu Jeronimo",

  // ── October ──────────────────────────────────────────────────────────────
  "10-1":  "Mutagatifu Tereza wa Lisieux",
  "10-2":  "Abamarayika Barinda",
  "10-4":  "Mutagatifu Fransisiko wa Asisi",
  "10-6":  "Mutagatifu Bruno",
  "10-7":  "Bikira Mariya wa Rozari",
  "10-9":  "Mutagatifu Denisi n'Inshuti ze na Mutagatifu Yohani Leonarudi",
  "10-11": "Mutagatifu Yohani XXIII",
  "10-14": "Mutagatifu Kalisito I",
  "10-15": "Mutagatifu Tereza w'Avila",
  "10-16": "Mutagatifu Edwigi na Mutagatifu Margarita Mariya Alakoki",
  "10-17": "Mutagatifu Ignasi wa Antiyokiya",
  "10-18": "Mutagatifu Luka (Umunyamakuru w'Ubutumwa bwiza)",
  "10-19": "Mutagatifu Yohani wa Brebeuf n'Inshuti ze",
  "10-22": "Mutagatifu Yohani Paulo II",
  "10-23": "Mutagatifu Yohani wa Kapistranu",
  "10-24": "Mutagatifu Antuwani Karini",
  "10-28": "Mutagatifu Simoni na Mutagatifu Yuda (Intumwa)",

  // ── November ─────────────────────────────────────────────────────────────
  "11-1":  "Ibadirishwa ry'Abatagatifu bose",
  "11-2":  "Gusenga Abamarayika Yose (Kwibuka Abapfuye bose)",
  "11-3":  "Mutagatifu Maretino wa Poresi",
  "11-4":  "Mutagatifu Karolo Boromeyo",
  "11-9":  "Gushyirwa kwa Bazirika ya Laterani",
  "11-10": "Mutagatifu Layo Nkuru",
  "11-11": "Mutagatifu Maretino wa Turo",
  "11-12": "Mutagatifu Yosafati",
  "11-13": "Mutagatifu Fransisikazi Kabrini",
  "11-15": "Mutagatifu Albertu Nkuru",
  "11-16": "Mutagatifu Margarita wa Ikoti na Mutagatifu Gertrudi",
  "11-17": "Mutagatifu Elizabeti wa Ugiriya",
  "11-18": "Gushyirwa kwa Bazirika ya Mutagatifu Petero na Mutagatifu Paulo",
  "11-21": "Gushyirwa kwa Bikira Mariya mu Hekalu",
  "11-22": "Mutagatifu Sesilia",
  "11-23": "Mutagatifu Kolombani",
  "11-24": "Mutagatifu Andire Dung-Lac n'Inshuti ze",
  "11-25": "Mutagatifu Katarini wa Aleksanderiya",
  "11-30": "Mutagatifu Andire (Intumwa)",

  // ── December ─────────────────────────────────────────────────────────────
  "12-3":  "Mutagatifu Fransisiko Kabiyo",
  "12-4":  "Mutagatifu Yohani wa Damasi",
  "12-6":  "Mutagatifu Niyikola",
  "12-7":  "Mutagatifu Amurosi",
  "12-8":  "Gusemwa kwa Bikira Mariya",
  "12-9":  "Ukundwa Wani Diego",
  "12-11": "Mutagatifu Damasi I",
  "12-12": "Bikira Mariya wa Gudalupi",
  "12-13": "Mutagatifu Lusiya",
  "12-14": "Mutagatifu Yohani wa Umusalaba",
  "12-21": "Mutagatifu Petero Kanizi",
  "12-23": "Mutagatifu Yohani wa Kanteni",
  "12-25": "Kuvuka kwa Yezu Kristu — Noheli",
  "12-26": "Mutagatifu Esitiyefano (Intumwa ya Mbere)",
  "12-27": "Mutagatifu Yohani (Intumwa na Umunyamakuru w'Ubutumwa bwiza)",
  "12-28": "Bana Batagatifu (Abahungu Barokotse)",
  "12-29": "Mutagatifu Toma wa Kanterubeyi",
  "12-31": "Mutagatifu Silvesiteru I",
};

/**
 * Returns today's saint name from the static calendar,
 * or null if there is no specific celebration today.
 */
export function getSaintOfDay(date: Date): string | null {
  const key = `${date.getMonth() + 1}-${date.getDate()}`;
  return SAINTS[key] ?? null;
}
