---
#title: "Personal Website"
image: pic1.HEIC
toc: false
about: 
  template: jolla
  image-shape: round
  image-width: 17em
  links: 
    - text: Linkedin
      href: linkedin.com/in/mizeroines
    - text: Email
      href: mailto:iinezazmizero@middlebury.edu
---

Hi there! My name is Ineza Mizero Ines Kevine, a junior at Middlebury College majoring in Computer Science with a focus in Electronics. I am originally from Kigali, Rwanda, and I am passionate about technology and how it can be leveraged to create meaningful impact. I love building and understanding systems; currently, I am constructing an 8-bit computer, which has deepened my excitement for hardware and engineering. I also work on projects that expand access and inclusion, such as developing a Virtual Campus Tour to help international students experience Middlebury remotely. This is an idea came to mind when I worked as an admissions assistant welcoming visitors and noticed the lack of international visitors from countries like Asia and Africa. This took me back to how much I wanted to see more than what was online about the school but could not because of distance. I am a dedicated, fast learner with strong communication and collaboration skills. I am eager to take on opportunities that allow me to grow and contribute to impactful work in Electronics and Computer Science to my country and the world.